[package]
name = "embree_sys"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
cmake = "0.1.49"
sha2 = "0.10"

[features]
default = []

